package Day3_SwingGUI;
import javax.swing.*;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame{
    //Create new form login
    public Login(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
@SuppressWarnings("unchecked")
private void initComponents() {

}

}
